import Head from "next/head";
import SideNavbar from "../components/SideNavbar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Responsive FullScreen Navbar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pro.ico" />
      </Head>
     <SideNavbar/>
     <h1 className="text-6xl text-center mt-32 mx-20 font-bold">Responsive FullScreen Navigation Bar using  <span className="text-red-500">Next.js</span> & <span className="text-blue-500">TailwindCSS</span></h1>
    </div>
  );
}
